// Execution-robustness runs in the user's SKYFORGE simulator: each concept at elite/strong/average tier
// in its natural alliance slot, against the simulator's reference alliance. Writes sim/results.json.
import { execFileSync } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { CONCEPTS } from '../robots.mjs';

const here = new URL('./', import.meta.url);
const gameDir = process.env.SKYFORGE_GAME_DIR ?? 'C:/Users/lidor/FRC/2026/mocked_game';
const simDir = `${gameDir}/sim`;
const sims = Number(process.env.SKYFORGE_SIMS ?? 120);
const tiers = ['elite', 'strong', 'average'];
const endgame = { SF1: 'hang', SF2: 'under', SF3: 'hang', SF4: 'hang', SF5: 'hang', SF6: 'hang', SF7: 'hang', SF8: 'hang' };
const slot = { SF1: ['Tower', 'LowRider'], SF2: ['Tower', 'LowRider'], SF3: ['Launcher', 'LowRider'], SF4: ['Launcher', 'LowRider'], SF5: ['Tower', 'LowRider'], SF6: ['Tower', 'LowRider'], SF7: ['Tower', 'LowRider'], SF8: ['Tower', 'LowRider'] };

const archetypes = Object.fromEntries(CONCEPTS.map(item => [item.id, { ...item.sim, description: `${item.id} ${item.name} (concept estimate)` }]));
const robots = {}, alliances = {}, rows = [];
for (const item of CONCEPTS) {
  const row = { label: `${item.id} ${item.name} + ${slot[item.id].join(' + ')}`, alliances: {} };
  for (const tier of tiers) {
    robots[`${item.id}_${tier}`] = { archetype: item.id, tier, endgame: endgame[item.id] };
    const name = `${item.id} ${tier}`;
    alliances[name] = [`${item.id}_${tier}`, ...slot[item.id]];
    row.alliances[tier] = name;
  }
  rows.push(row);
}
// Controls: remove the concept-specific accuracy assumptions to see how much of each result they carry.
const controls = [
  { id: 'SF3', key: 'SF3_noFork', label: 'SF3 control: your Tower task times and accuracies (no fork bonus)', patch: { tasks: { G1: [0.6, 0.8, 0.92], G2: [0.9, 0.85, 0.93], G3: [1.5, 1.05, 0.9] } } },
  { id: 'SF1', key: 'SF1_lowShot', label: 'SF1 control: your short-launcher VG accuracy (0.78)', patch: { tasks: { VG: [0.8, 0.6, 0.78], G1: null }, defense_sensitivity: 1.0 } },
  { id: 'SF8', key: 'SF8_noDunk', label: 'SF8 control: SF6 trapdoor time and accuracy (no dunk bonus)', patch: { tasks: { G1: null, G2: [0.8, 0.45, 0.93], G3: [1.0, 0.45, 0.93], VG: [0.9, 0.45, 0.85] } } },
];
for (const control of controls) {
  archetypes[control.key] = { ...archetypes[control.id], ...control.patch, description: control.label };
  const row = { label: `${control.label} + ${slot[control.id].join(' + ')}`, alliances: {} };
  for (const tier of tiers) {
    robots[`${control.key}_${tier}`] = { archetype: control.key, tier, endgame: endgame[control.id] };
    const name = `${control.key} ${tier}`;
    alliances[name] = [`${control.key}_${tier}`, ...slot[control.id]];
    row.alliances[tier] = name;
  }
  rows.push(row);
}
for (const [preset, partners, end] of [['Launcher', ['Tower', 'LowRider'], 'hang'], ['Tower', ['Launcher', 'LowRider'], 'hang']]) {
  const row = { label: `Your ${preset} preset + ${partners.join(' + ')}`, alliances: {} };
  for (const tier of tiers) {
    robots[`${preset}_${tier}`] = { archetype: preset.toLowerCase(), tier, endgame: end };
    const name = `${preset} preset ${tier}`;
    alliances[name] = [`${preset}_${tier}`, ...partners];
    row.alliances[tier] = name;
  }
  rows.push(row);
}
const reference = 'REF Tower+Launcher+LowRider';
alliances[reference] = ['Tower', 'Launcher', 'LowRider'];
const config = {
  _note: 'Generated by trials/skyforge-concepts/sim/run.mjs. Concept archetypes are design estimates, not measured robots.',
  name: 'skyforge_concepts_robustness', sims, seed: 2026, strategy: { rp_mode: 'quals', rp_value_pts: 15 },
  archetypes, robots, alliances,
  matchups: Object.keys(alliances).filter(name => name !== reference).map(name => [name, reference]),
};
await mkdir(new URL('runs/', here), { recursive: true });
const configPath = fileURLToPath(new URL('config.json', here));
await writeFile(configPath, `${JSON.stringify(config, null, 1)}\n`);
const out = fileURLToPath(new URL('runs/latest/', here));
const started = Date.now();
// SKYFORGE_SIM_REUSE=1 re-reads runs/latest (same config) instead of re-simulating.
if (process.env.SKYFORGE_SIM_REUSE !== '1') execFileSync('python', ['-m', 'skyforge_sim', configPath, '--out', out, '--no-events', '--no-timeline'], { cwd: simDir, stdio: 'inherit' });
const summary = JSON.parse(await readFile(`${out}/summary.json`, 'utf8'));
// Newer simulator versions nest the matchups under `batch`.
const matchups = summary.matchups ?? summary.batch?.matchups;
const find = name => {
  const matchup = matchups.find(entry => entry.red.alliance === name || entry.blue?.alliance === name);
  const side = matchup.red.alliance === name ? matchup.red : matchup.blue;
  return { win: side.win_pct, rp: side.mean.rp, score: side.mean.score, levels: side.mean.rp_levels * 100, skyforge: side.mean.rp_skyforge * 100, board: side.mean.rp_board * 100 };
};
const result = {
  note: `${sims} matches per row per tier against your simulator's reference alliance (${reference}, all strong). Our robot takes the listed slot; its tier changes, and the partners stay strong. Tiers come from your simulator: average means slower cycles, lower accuracy and more jams and failures than strong.`,
  caveat: 'Concept numbers (cycle, accuracy, complexity) are my estimates entered into your model, shown next to your presets in the same slot. This measures sensitivity inside the simulator, not real robot performance.',
  tiers, source: { simulator: simDir, configSha256: createHash('sha256').update(await readFile(configPath)).digest('hex'), seconds: Math.round((Date.now() - started) / 1000) },
  rows: rows.map(row => ({ label: row.label, byTier: Object.fromEntries(tiers.map(tier => [tier, find(row.alliances[tier])])) })),
};
await writeFile(new URL('results.json', here), `${JSON.stringify(result, null, 1)}\n`);
console.log(`Simulator robustness: ${rows.length} rows x ${tiers.length} tiers, ${result.source.seconds} s.`);
