import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {build} from '../../trials/whole-robot-concepts/mechanisms/node_modules/esbuild/lib/main.js';

const root=new URL('./',import.meta.url),output=new URL('output/',root);
const pickup=JSON.parse(readFileSync(new URL('pickup-mesh.json',output)));
const report=JSON.parse(readFileSync(new URL('pickup-report.json',root)));
const old=JSON.parse(readFileSync(new URL('../coral-intake-v1/checkpoint/viewer-data.json',root)));
const referenceInstances=pickup.reference_only.instances.filter(part=>part.category==='reference_indexer').map(part=>({id:part.id,definition:part.definition,matrix:part.matrix}));
const referenceMeshes=Object.fromEntries([...new Set(referenceInstances.map(part=>part.definition))].map(name=>[name,old.meshes[name]]));
const oldInstance=old.manifest.instances.find(part=>part.id==='pickup_crossmember_0');
const data={pickup,references:{instances:referenceInstances,meshes:referenceMeshes},oldTube:{instance:oldInstance,geometry:old.meshes[oldInstance.definition]}};
const bundle=await build({entryPoints:[fileURLToPath(new URL('viewer.mjs',root))],bundle:true,write:false,minify:true,format:'esm',legalComments:'none'});
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Coral Pickup / Revision 2</title><style>
:root{--ink:#263a32;--muted:#5b7265;--line:#c1cfc7;--warn:#9b4030}*{box-sizing:border-box}body{margin:0;font-family:Georgia,serif;letter-spacing:0;background:#eef2f0;color:var(--ink)}header{display:flex;justify-content:space-between;align-items:center;gap:15px;flex-wrap:wrap;padding:14px 20px;background:white;border-bottom:1px solid var(--line)}h1{font-size:22px;margin:0}nav{display:flex;gap:14px;flex-wrap:wrap;font-size:13px}a{color:#236f60}.toolbar{display:flex;gap:14px;flex-wrap:wrap;align-items:center;padding:10px 20px;background:#f7faf8;border-bottom:1px solid var(--line)}label{display:flex;gap:7px;align-items:center;font-size:13px}select{font:13px Georgia,serif;max-width:100%;padding:6px;border:1px solid #9db4a7;background:white;border-radius:3px}.workspace{display:grid;grid-template-columns:minmax(0,1fr) 255px}#scene{min-width:0;height:calc(100dvh - 230px);min-height:410px}canvas{display:block;max-width:100%;touch-action:none}aside{padding:18px;background:white;border-left:1px solid var(--line)}h2{font-size:17px;margin:0 0 12px}.status{color:var(--warn);font-size:12px;font-weight:bold;margin-bottom:20px}dl{display:grid;grid-template-columns:1fr auto;gap:10px;font-size:13px}dd{margin:0;text-align:right}p{font-size:12px;line-height:1.6}.controls{display:flex;gap:20px;flex-wrap:wrap;padding:12px 20px;border-top:1px solid var(--line);background:white}input[type=range]{width:145px;accent-color:#247456}output{width:66px;font-variant-numeric:tabular-nums;text-align:right}footer{padding:10px 20px;background:#fff5ec;color:var(--warn);font-size:12px}@media(max-width:760px){header,.toolbar,.controls{padding:12px;gap:11px}.workspace{grid-template-columns:1fr}#scene{height:58dvh;min-height:390px}aside{border-left:0;border-top:1px solid var(--line)}dl{grid-template-columns:1fr auto 1fr auto;gap:8px}h1{font-size:20px}}
</style></head><body><header><h1>Coral Pickup / Revision 2</h1><nav><a href="assembly.step">Pickup STEP</a><a href="../DECISIONS.md">Design Decisions</a><a href="../../coral-intake-v1/checkpoint/index.html">Previous Full Draft</a></nav></header><div class="toolbar"><label>View<select id="view"><option value="iso">Isometric</option><option value="side">Side</option><option value="front">Front</option><option value="top">Top</option></select></label><label><input id="reference" type="checkbox" checked>Old indexer reference</label><label><input id="context" type="checkbox" checked>Frame + bumper</label><label><input id="old" type="checkbox">Old blocking tube</label><label><input id="piece" type="checkbox" checked>Coral</label><label>Yaw<select id="yaw"><option value="90">Crosswise / 90 deg</option><option value="60">60 deg</option><option value="30">30 deg</option><option value="0">Lengthwise / 0 deg</option></select></label></div><div class="workspace"><main id="scene"></main><aside><h2>Direct-Bearing Pickup</h2><div class="status">STRUCTURE ONLY / NOT RELEASED</div><dl><dt>Machined definitions</dt><dd>${report.inventory.unique_machined_definitions}</dd><dt>Cut-stock definitions</dt><dd>${report.inventory.cut_only_definitions.length}</dd><dt>Instances</dt><dd>${report.inventory.instances}</dd><dt>Front row span</dt><dd>393.7 mm</dd><dt>Pivot height</dt><dd>330 mm</dd><dt>Stow rotation</dt><dd>140 deg</dd></dl><p>Green: original AndyMark stars.<br>Silver: new custom structure.<br>Blue: old indexer, reference only.<br>Red tube: rejected obstruction.</p><p>Deployment drive, mounts, power transmission and continuous acquisition remain unresolved.</p></aside></div><div class="controls"><label>Fold<input id="fold" type="range" min="0" max="140" value="0"><output id="foldValue">0 deg</output></label><label>Float<input id="float" type="range" min="0" max="8" value="0"><output id="floatValue">0 deg</output></label><label>Coral Y<input id="approach" type="range" min="-450" max="-200" step="1" value="-365"><output id="approachValue">-365 mm</output></label></div><footer>Unpowered approach and sample-clearance study. Not a complete intake or field-reliability demonstration.</footer><script>window.pickupData=${JSON.stringify(data).replaceAll('<','\\u003c')};</script><script type="module">${bundle.outputFiles[0].text.replaceAll('</script','<\\/script')}</script></body></html>`;
const page=html.replace('<label><input id="reference"','<label>Framing<select id="framing"><option value="current">Current pose</option><option value="motion">Motion envelope</option></select></label><label><input id="reference"');
writeFileSync(new URL('index.html',output),page);
writeFileSync(new URL('viewer-manifest.json',output),JSON.stringify({instances:pickup.instances.length,referenceInstances:referenceInstances.length,meshSha256:createHash('sha256').update(readFileSync(new URL('pickup-mesh.json',output))).digest('hex'),htmlSha256:createHash('sha256').update(page).digest('hex'),release:false},null,2));
console.log(JSON.stringify({instances:pickup.instances.length,referenceInstances:referenceInstances.length,bytes:Buffer.byteLength(html),file:fileURLToPath(new URL('index.html',output))}));