import {build} from 'esbuild';
import {mkdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {intakeRecipes} from './intake-models.mjs';

const output=new URL('../../../outputs/concepts/mechanisms/',import.meta.url);
await mkdir(output,{recursive:true});
const bundle=await build({entryPoints:[new URL('intake-viewer.mjs',import.meta.url).pathname.replace(/^\/([A-Za-z]:)/,'$1')],bundle:true,format:'iife',write:false,minify:true,legalComments:'none',platform:'browser'});
const bytes=bundle.outputFiles[0].contents;await writeFile(new URL('viewer.js',output),bytes);
const esc=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Intake Mechanism States</title><style>
:root{--ink:#263934;--muted:#596e64;--line:#ced9d1;--accent:#286a70}*{box-sizing:border-box}body{margin:0;color:var(--ink);background:#edf2ee;font-family:Georgia,serif;letter-spacing:0}header{padding:18px 24px;background:white;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}h1{font-size:24px;margin:0}h2{font-size:23px;margin:8px 0 14px;overflow-wrap:anywhere}h3{font-size:16px;margin:18px 0 6px}p{font-size:15px;line-height:1.55}a{color:var(--accent)}nav{line-height:1.8}.toolbar{padding:12px 24px;display:flex;gap:14px;flex-wrap:wrap;align-items:end;border-bottom:1px solid var(--line);background:#fafcfa}label{font-size:13px;display:grid;gap:5px;color:var(--muted)}select{font:15px Georgia,serif;min-height:38px;max-width:100%;padding:7px 26px 7px 9px;color:var(--ink);background:white;border:1px solid #aebfb3;border-radius:3px}.workspace{display:grid;grid-template-columns:minmax(0,1fr) 320px}.viewport{min-width:0;position:relative}#scene{width:100%;height:680px}canvas{display:block;touch-action:none}.stamp{position:absolute;bottom:12px;left:15px;font-size:11px;background:#f2f5f3d9;padding:5px 7px;pointer-events:none}.detail{background:white;border-left:1px solid var(--line);padding:20px}.warning{color:#864339}.band{max-width:1700px;margin:auto;padding:26px 24px;border-top:1px solid var(--line)}.sheet{width:100%;height:auto;display:block}.states{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:18px}.states a{text-decoration:none}.states img{width:100%;aspect-ratio:1.3;object-fit:contain;background:#f2f5f3}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.item{text-decoration:none;border-bottom:2px solid transparent;padding-bottom:8px}.item.selected{border-color:var(--accent)}.item img{width:100%;aspect-ratio:1.3;object-fit:contain;background:#f2f5f3;display:block}.item strong{display:block;margin-top:8px;font-size:16px}.muted{color:var(--muted);font-size:13px}footer{padding:24px;line-height:1.7;background:white;border-top:1px solid var(--line)}@media(max-width:900px){.workspace{grid-template-columns:minmax(0,1fr) 280px}.detail{padding:15px}.grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:650px){header,.toolbar{padding:14px}.toolbar label:first-child{width:100%}.workspace{display:block}#scene{height:460px}.detail{border-left:0;border-top:1px solid var(--line)}.band{padding:22px 14px}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.states{gap:6px;font-size:13px}.stamp{left:8px;right:8px;font-size:10px}h1{font-size:22px}select{font-size:14px}}</style></head><body>
<header><div><h1>Coral Intake / Mechanism States</h1><p class="muted">14 concepts / Open, collapsed, handoff / untested</p></div><nav><a href="../index.html">Original 2D flow gallery</a> · <a href="../../whole-robots/mechanisms/index.html">Whole-robot scenes</a> · <a href="README.md">Evidence and limits</a></nav></header>
<div id="viewer"><div class="toolbar"><label>Intake<select id="robot">${intakeRecipes.map(recipe=>`<option value="${recipe.id}">${recipe.id} / ${esc(recipe.title)}</option>`).join('')}</select></label><label>Configuration<select id="pose"><option value="open">Open / floor coral</option><option value="collapsed">Collapsed / retained coral</option><option value="handoff">Handoff / receiver</option></select></label><label>View<select id="view"><option value="iso">Isometric</option><option value="side">Side</option><option value="front">Front</option><option value="top">Top</option></select></label><a id="download" href="intake-01-open.png">State PNG</a></div><div class="workspace"><div class="viewport"><div id="scene"></div><div class="stamp">ONE CORAL / PROPOSED POSES, NOT VERIFIED MOTION OR CONTACT</div></div><aside class="detail"><h2 id="title"></h2><p id="description"></p><h3>Collapse Intent</h3><p id="stow"></p><p id="receiver" class="muted"></p><h3>Main Risk</h3><p id="risk"></p><p id="warning" class="warning"></p><details><summary>First Cheap Test</summary><p id="first-test"></p></details></aside></div></div>
<section class="band"><h2>Open / Collapsed / Handoff</h2><a id="state-link" href="intake-01-states.png"><img class="sheet" id="state-sheet" src="intake-01-states.png" alt="Three intake configurations at a common camera scale"></a><div class="states">${[['open','Open'],['collapsed','Collapsed'],['handoff','Handoff']].map(([pose,label])=>`<a data-pose="${pose}" href="#viewer"><img src="intake-01-${pose}.png" alt="${label} intake pose"><strong>${label}</strong></a>`).join('')}</div></section>
<section class="band"><h2>Original 2D Geometry And Flow</h2><a id="flow-link" href="../concept-01.png"><img class="sheet" id="flow" src="../concept-01.png" alt="Original side and top flow-path drawing, unchanged"></a></section>
<section class="band"><h2>Fourteen Intake Suggestions</h2><div class="grid">${intakeRecipes.map(recipe=>`<a class="item" data-id="${recipe.id}" href="?intake=${recipe.id}#viewer"><img src="intake-${recipe.id}-open.png" alt="${esc(recipe.title)} 3D intake mockup"><strong>${recipe.id} / ${esc(recipe.title)}</strong></a>`).join('')}</div></section>
<footer>3D mockups complement the original 2D path drawings. Mouth/receiver datums are retained; detailed shapes and moving poses are illustrative reconstructions, not solved mechanisms. Option 12 retains its explicit 2025 bumper-rule conflict. No CAD kernel or Onshape calls.</footer><script src="viewer.js"></script></body></html>`;
await writeFile(new URL('index.html',output),html);
await writeFile(new URL('manifest.json',output),`${JSON.stringify({status:'INTAKE_STATES_COMPLEMENT_2D',count:14,states:3,apiCalls:0,cadKernelRuns:0,bundleSha256:createHash('sha256').update(bytes).digest('hex'),originalFlowDrawingsPreserved:true},null,2)}\n`);
console.log('Built standalone intake mechanism viewer: 14 intakes x 3 states; original 2D sheets referenced unchanged.');