const esc=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');

export function renderConceptHome(robots){
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>REEFSCAPE Robot Concepts</title><style>
:root{--ink:#263934;--muted:#5b6f65;--line:#ced9d1;--accent:#256c72}*{box-sizing:border-box}body{margin:0;background:#edf2ee;color:var(--ink);font-family:Georgia,serif;letter-spacing:0}header{padding:20px 26px;background:white;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:14px;flex-wrap:wrap}h1{font-size:27px;margin:0}header p{font-size:14px;color:var(--muted);margin:7px 0 0}nav{font-size:14px;line-height:1.8}a{color:var(--accent)}main{max-width:1800px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:22px 18px}.concept{display:block;text-decoration:none;border:1px solid var(--line);border-radius:5px;overflow:hidden;background:white;color:var(--ink)}.concept:hover,.concept:focus-visible{border-color:var(--accent);outline:2px solid var(--accent);outline-offset:2px}.concept img{width:100%;height:auto;aspect-ratio:1.3;object-fit:contain;display:block;background:#f2f5f3}.caption{padding:12px 14px 15px}h2{font-size:19px;line-height:1.25;margin:0 0 8px;overflow-wrap:anywhere}.caption p{font-size:13px;line-height:1.55;margin:4px 0;color:var(--muted)}footer{padding:20px 26px;border-top:1px solid var(--line);font-size:13px;line-height:1.6}@media(max-width:1150px){.grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:760px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}main{padding:15px}.caption{padding:10px}h2{font-size:17px}header{padding:17px}}@media(max-width:420px){.grid{gap:12px 10px}h2{font-size:15px}.caption p{font-size:12px}}</style></head><body>
<header><div><h1>REEFSCAPE / Robot Concepts</h1><p>Ten 2025 architectures / coral, algae and endgame / untested concept geometry</p></div><nav><a href="interactions/index.html">Task comparisons</a> · <a href="../../concepts/mechanisms/index.html">Intake concepts + 2D flows</a> · <a href="interactions/README.md">Geometry limits</a></nav></header>
<main><div class="grid">${robots.map(robot=>{const cap=robot.capabilities;return `<a class="concept" data-robot="${robot.id}" href="viewer.html?robot=${robot.id}"><img src="robot-${robot.id}.png" width="1375" height="1062" alt="${esc(robot.title)} mechanism preview"><div class="caption"><h2>${robot.id} / ${esc(robot.title)}</h2><p>Coral ${cap.coralLevels.map(level=>`L${level}`).join('/')} · ${cap.coralSources.join(' + ')}</p><p>Algae ${cap.algaeDestinations.join(' + ')} · ${cap.climb} endgame</p></div></a>`;}).join('')}</div></main>
<footer>Capabilities are design intentions, not validated performance. The task viewer identifies unresolved reach and extension limits. <a href="README.md">Architecture review</a> · <a href="states/index.html">Earlier configuration sheets</a></footer>
<script>if(new URLSearchParams(location.search).has('robot')||new URLSearchParams(location.search).has('task'))location.replace('viewer.html'+location.search+location.hash);</script></body></html>`;
}